### ISSUE TITLE
serviceAddress is null

### ISSUE THREAD

**Issue by junzew** [markrjr/Salut#33]
I am using Salut 0.5.0 and I have two client devices and a host successfully connected to each other. 
Communication between host and client works fine. However, when I invoke sendToDevice to try to send some data from one client to another client:
```           
network.sendToDevice(anotherClientDevice, data, new SalutCallback() {
        @Override
        public void call() {
            Log.d(TAG, "send data to device failed");
        }
    }
);
```
I got the following exception:
java.lang.IllegalArgumentException: host=null, port=4321
    at java.net.InetSocketAddress.<init>(InetSocketAddress.java:99)
    at java.net.InetSocketAddress.<init>(InetSocketAddress.java:90)
    at com.peak.salut.BackgroundDataSendJob.doOnBackground(BackgroundDataSendJob.java:37)
    at com.arasthel.asyncjob.AsyncJob$2.run(AsyncJob.java:59)
    at java.lang.Thread.run(Thread.java:818)

It turns out that `device.serviceAddress` is `null` in `BackgroundDataSendJob`:
```
try {
     dataSocket.connect(new InetSocketAddress(device.serviceAddress, device.servicePort));
     // ...
}
```
The field `Salut.serviceAddress` seems to be not properly set in `BackgroundClientRegistrationJob` and `BackgroundServerRegistrationJob`.

Any thoughts on this?

**Comment by VitorFontenelle** [comment]
I have the same issue. If you got any answers, please share them here.

**Comment by neatorobito** [comment]
Can you try using 0.4.9?
    compile 'com.github.markrjr:Salut:v0.4.9'

**Comment by VitorFontenelle** [comment]
I have tried to downgrade to 0.5.0 and 0.4.9, and for some reason, in these versions the Client don't even discover the Host... I have ended up opening a new issue with more details on my specific case. [https://github.com/markrjr/Salut/issues/35](url)
